version: '3.1'
services:
  snow-zloradnij:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: snow_start
    container_name: snow_start-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.snow-zloradnij.entrypoints=http"
      - "traefik.http.routers.snow-zloradnij.rule=Host(`www.snow.zloradnij.ru`,`snow.zloradnij.ru`)"  ## Hier eure Domain eingeben ##
      - "traefik.http.middlewares.snow.zloradnij-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.snow-zloradnij.middlewares=snow-zloradnij-https-redirect"
      - "traefik.http.routers.snow-zloradnij-secure.entrypoints=https"
      - "traefik.http.routers.snow-zloradnij-secure.rule=Host(`www.snow.zloradnij.ru`,`snow.zloradnij.ru`)" ## Hier eure Domain eingeben ##
      - "traefik.http.routers.snow-zloradnij-secure.tls=true"
      - "traefik.http.routers.snow-zloradnij-secure.tls.certresolver=http"
      - "traefik.http.routers.snow-zloradnij-secure.service=snow-zloradnij"
      - "traefik.http.services.snow-zloradnij.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - default

networks:
  proxy:
    external: true
